version: '2'
services:
  frontend:
    container_name: imob-ft
    image: egito/angular
    volumes:
      - ${PWD}/:/app
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/share/code/:/usr/share/code
      - ${PWD}/:/root
    ports:
      - 8443:443
      - 80:4200

  backend:
    container_name: imob-bk
    extends:
      file: imob-bk-${TIPO}/common-services.yml
      service: imob-bk
    depends_on:
      - imob-db
      - imob-pgadmin

  imob-db:
    container_name: imob-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=salvador
      - POSTGRES_PASSWORD=salvador!
    restart: always
    volumes:
      - /home/pg_data:/var/lib/postgresql/data
      - ${PWD}/imob-bk-hasura/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #command: createdb -O postgres imob
    #command: createdb blog1

  imob-pgadmin:
    container_name: imob-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "josedoegito@msn.com"
      PGADMIN_DEFAULT_PASSWORD: "egito!"
    ports:
      - "8081:80"
    depends_on:
      - imob-db
